"use client";
import { Flex, Text } from "@chakra-ui/react";
import Link from "next/link";
import Head from "next/head";

import { ConnectButton } from '@rainbow-me/rainbowkit';

const Header = () => {
  return (
    <>
      <Head>
          <title>BBK Minting DApp</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link rel="icon" href="/favicon.ico" /> 
      </Head>
      <Flex h="15vh" p="2rem" justifyContent="space-between" alignItems="center">
          <Text>BBK Minting DApp</Text>
          <ConnectButton />
      </Flex>
    </>
  )
}

export default Header